---
title: 'Özel durumlar: Failwith işlevi'
description: Nasıl 'failwith' işlevi oluşturur öğrenin bir F# özel durum.
ms.date: 05/16/2016
ms.openlocfilehash: 05d385ddfc98a910779a6f59949a7187c38f0812
ms.sourcegitcommit: fa38fe76abdc8972e37138fcb4dfdb3502ac5394
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 12/19/2018
ms.locfileid: "53610118"
---
# <a name="exceptions-the-failwith-function"></a><span data-ttu-id="4dcdb-103">Özel durumlar: Failwith işlevi</span><span class="sxs-lookup"><span data-stu-id="4dcdb-103">Exceptions: The failwith Function</span></span>

<span data-ttu-id="4dcdb-104">`failwith` İşlevi oluşturur bir F# özel durum.</span><span class="sxs-lookup"><span data-stu-id="4dcdb-104">The `failwith` function generates an F# exception.</span></span>

## <a name="syntax"></a><span data-ttu-id="4dcdb-105">Sözdizimi</span><span class="sxs-lookup"><span data-stu-id="4dcdb-105">Syntax</span></span>

```fsharp
failwith error-message-string
```

## <a name="remarks"></a><span data-ttu-id="4dcdb-106">Açıklamalar</span><span class="sxs-lookup"><span data-stu-id="4dcdb-106">Remarks</span></span>

<span data-ttu-id="4dcdb-107">*Hata iletisi dizesi* önceki sözdiziminde bir değişmez değer dize türünde bir değer mi `string`.</span><span class="sxs-lookup"><span data-stu-id="4dcdb-107">The *error-message-string* in the previous syntax is a literal string or a value of type `string`.</span></span> <span data-ttu-id="4dcdb-108">Bu duruma `Message` özel durumun özelliği.</span><span class="sxs-lookup"><span data-stu-id="4dcdb-108">It becomes the `Message` property of the exception.</span></span>

<span data-ttu-id="4dcdb-109">Tarafından oluşturulan özel durum `failwith` olduğu bir `System.Exception` adına sahip bir başvurudur özel durum `Failure` içinde F# kod.</span><span class="sxs-lookup"><span data-stu-id="4dcdb-109">The exception that is generated by `failwith` is a `System.Exception` exception, which is a reference that has the name `Failure` in F# code.</span></span> <span data-ttu-id="4dcdb-110">Aşağıdaki kod kullanışını `failwith` özel durum oluşturabilir.</span><span class="sxs-lookup"><span data-stu-id="4dcdb-110">The following code illustrates the use of `failwith` to throw an exception.</span></span>

[!code-fsharp[Main](../../../../samples/snippets/fsharp/lang-ref-2/snippet6001.fs)]

## <a name="see-also"></a><span data-ttu-id="4dcdb-111">Ayrıca bkz.</span><span class="sxs-lookup"><span data-stu-id="4dcdb-111">See also</span></span>

- [<span data-ttu-id="4dcdb-112">Özel Durum İşleme</span><span class="sxs-lookup"><span data-stu-id="4dcdb-112">Exception Handling</span></span>](index.md)
- [<span data-ttu-id="4dcdb-113">Özel Durum Türleri</span><span class="sxs-lookup"><span data-stu-id="4dcdb-113">Exception Types</span></span>](exception-types.md)
- [<span data-ttu-id="4dcdb-114">Özel durumlar: `try...with` İfadesi</span><span class="sxs-lookup"><span data-stu-id="4dcdb-114">Exceptions: The `try...with` Expression</span></span>](the-try-with-expression.md)
- [<span data-ttu-id="4dcdb-115">Özel durumlar: `try...finally` İfadesi</span><span class="sxs-lookup"><span data-stu-id="4dcdb-115">Exceptions: The `try...finally` Expression</span></span>](the-try-finally-expression.md)
- [<span data-ttu-id="4dcdb-116">Özel durumlar: `raise` işlevi</span><span class="sxs-lookup"><span data-stu-id="4dcdb-116">Exceptions: the `raise` Function</span></span>](the-raise-function.md)