---
title: "'Çıkış deneyin' yalnızca bir 'Try' deyiminin içinde yer alabilir"
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: d07afdb2c6026028e765173b87e869aedb0d3155
ms.sourcegitcommit: 0888d7b24f475c346a3f444de8d83ec1ca7cd234
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 12/22/2018
ms.locfileid: "53763545"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Çıkış deneyin' yalnızca bir 'Try' deyiminin içinde yer alabilir
`Exit Try` yalnızca içinde görünebilir bir `Try` deyimi engelleyin. Ya da bir yedek sahip `Exit Try` deyimi veya `Exit Try` deyimi, karşılık gelen sınırları dışında görünür `Try` blok.  
  
 **Hata Kimliği:** BC30393  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
1.  Bulmak ve gereksiz kaldırma `Exit Try` deyimi.  
  
2.  Taşıma `Exit Try` kodunuz içinde uygun konuma deyimi.  
  
## <a name="see-also"></a>Ayrıca Bkz.  
 [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
